.MODEL SMALL
.STACK 100H
.DATA
    ARRAY   DB 45H, 12H, 78H, 03H, 99H, 56H
    COUNT   EQU 06H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    MOV CX, COUNT-1
OUTER_LOOP:
    PUSH CX
    LEA SI, ARRAY
INNER_LOOP:
    MOV AL, [SI]
    MOV BL, [SI+1]
    CMP AL, BL
    JBE NO_SWAP
    MOV [SI], BL
    MOV [SI+1], AL
NO_SWAP:
    INC SI
    LOOP INNER_LOOP
    POP CX
    LOOP OUTER_LOOP
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN