.MODEL SMALL
.STACK 100H
.DATA
    NUM     DB 05H
    RESULT  DW 0001H
    MSG     DB 10,13,"Factorial: $"
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    MOV CL, NUM
    MOV CH, 0
    MOV AX, 1
    CMP CX, 0
    JE STORE_RESULT
FACT_LOOP:
    MUL CX
    LOOP FACT_LOOP
STORE_RESULT:
    MOV RESULT, AX
    LEA DX, MSG
    MOV AH, 09H
    INT 21H
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN